### ISSUE TITLE
Differences between testvectors_v1 and testvectors

### ISSUE THREAD

**Issue by XuJiandong** [C2SP/wycheproof#119]
In https://github.com/C2SP/wycheproof/blob/master/doc/formats.md#test-vectors
> The old test vectors are in the directory wycheproof/testvectors/, while the new test vectors are in wycheproof/testvectors_v1/.

Does it mean that the `testvectors` is a subset of `testvectors_v1`? Can we only use test cases from `testvectors_v1`?

**Comment by bleichenbacher-daniel** [comment]
testvectors_v1 contains the latest version of the test vectors. The main reason for making a new directory is that the format of the test vectors has slightly changed, so that it was possible to add more comments describing the tests. The new files contain the test vectors from the old directory as well as some new ones. Some file (e.g., dsa_test.json or ecdh_test.json) have been split into multiple files, since the original file became too large. 

The JSON schemas do not appear to have been updated. They still describe the test vectors in the old testvectors/ directory.  However, there should not be any significant changes for the actual test vectors. 

Also, if there are any issues/annoyances with the test vectors or their format, please point them out. I'm currently rewriting the whole project and it would be a good time to learn about problems. There are already some open issues about potential changes.
